server:
  port: 8080
  session-timeout: 1800
spring:
  profiles:
    active: dev
  thymeleaf:
    mode: LEGACYHTML5       # 模板模式
    cache: false           # 禁用html缓存
#  devtools:
#    restart:
#      enabled: true
  cache:
    type: ehcache
    ehcache:
      config: classpath:config/ehcache.xml

mybatis:
  #type-aliases-package: com.bootdo.*.*.domain    # mybatis短名
  typeAliasesPackage: com.bootdo.system.domain, com.bootdo.common.domain
  mapper-locations: mybatis/**/*Mapper.xml      # 扫描mapper文件
  configuration:
    map-underscore-to-camel-case: true        # 支持下划线转驼峰
